POST http://localhost:3000/
Content-Type: application/json

[
  {
    "toppings": [
      {
        "name": "Ham"
      },
      {
        "name": "Mushrooms"
      },
      {
        "name": "Cheese"
      },
      {
        "name": "Cheese"
      },
      {
        "name": "Salami"
      }
    ]
  },
  {
    "toppings": [
      {
        "name": "Sauce"
      },
      {
        "name": "Cheese"
      },
      {
        "name": "Basil"
      }
    ]
  }
]
